# Generated by Django 5.2.14 on 2026-05-14 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('repository', 'Code Repository'), ('aws', 'AWS AI Service'), ('gcp', 'GCP AI Service'), ('azure', 'Azure AI Service'), ('local', 'Local Application'), ('api_endpoint', 'API Endpoint')], default='repository', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')], default='active', max_length=32)),
                ('repository_url', models.URLField(blank=True, help_text='GitHub/GitLab repository URL')),
                ('cloud_resource_id', models.CharField(blank=True, help_text='Cloud resource identifier', max_length=512)),
                ('api_endpoint', models.URLField(blank=True, help_text='API endpoint URL for monitoring')),
                ('local_path', models.CharField(blank=True, help_text='Local filesystem path', max_length=1024)),
                ('auto_scan_enabled', models.BooleanField(default=True, help_text='Enable automatic security scanning')),
                ('scan_schedule', models.CharField(default='0 */6 * * *', help_text='Cron expression for scheduled scans', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('code_security', 'Code Security'), ('model_artifact', 'Model Artifact'), ('dependency', 'Dependency Audit'), ('redteam', 'Red Team'), ('agent_forensics', 'Agent Forensics'), ('full', 'Full Security Scan')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('findings_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_project_slug_per_org'),
        ),
    ]
