# Generated by Django 5.x for gateway project support

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="gateway_agent_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Agent key when this project is a gateway-connected app",
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gateway_agent_key__gt", "")),
                fields=("organization", "gateway_agent_key"),
                name="unique_gateway_agent_key_per_org",
            ),
        ),
    ]
