# Generated by Django 5.2.14 on 2026-05-16 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_dashboard_project'),
        ('projects', '0002_project_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dashboard_project',
            field=models.ForeignKey(blank=True, help_text='Last project selected for the security dashboard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_focus_users', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='event_type',
            field=models.CharField(choices=[('organization_created', 'Organization created'), ('user_registered', 'Account registered'), ('user_login', 'Signed in'), ('user_logout', 'Signed out'), ('project_created', 'Project added'), ('project_deleted', 'Project deleted'), ('project_create_blocked', 'Project add blocked (limit)'), ('api_key_created', 'API key generated'), ('api_key_revoked', 'API key revoked')], db_index=True, max_length=64),
        ),
    ]
