# Generated by Django 5.2.14 on 2026-07-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_gatewayconnector"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="runtime_policy_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Workspace runtime policy (e.g. blocked_agent_keys).",
            ),
        ),
    ]
