# Generated by Django 5.2.14 on 2026-05-14 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.CharField(db_index=True, max_length=128)),
                ('parent_span_id', models.CharField(blank=True, max_length=128)),
                ('span_id', models.CharField(max_length=128)),
                ('trace_type', models.CharField(choices=[('llm_call', 'LLM Call'), ('tool_call', 'Tool Call'), ('agent_action', 'Agent Action'), ('retrieval', 'Retrieval'), ('embedding', 'Embedding')], max_length=32)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('blocked', 'Blocked'), ('timeout', 'Timeout')], default='success', max_length=32)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('input_text', models.TextField(blank=True)),
                ('output_text', models.TextField(blank=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_signals', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='projects.project')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['organization', 'trace_type'], name='security_ai_organiz_1ad50b_idx'), models.Index(fields=['organization', 'status'], name='security_ai_organiz_2dba2b_idx'), models.Index(fields=['trace_id'], name='security_ai_trace_i_6c3755_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_id', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('false_positive', 'False Positive'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=32)),
                ('source', models.CharField(blank=True, db_index=True, max_length=64)),
                ('category', models.CharField(blank=True, db_index=True, max_length=128)),
                ('subcategory', models.CharField(blank=True, max_length=128)),
                ('file_path', models.CharField(blank=True, max_length=1024)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('code_snippet', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('cwe', models.CharField(blank=True, max_length=32)),
                ('owasp_llm', models.CharField(blank=True, max_length=32)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='projects.project')),
            ],
            options={
                'ordering': ['-first_seen_at'],
                'indexes': [models.Index(fields=['organization', 'severity'], name='security_se_organiz_350bda_idx'), models.Index(fields=['organization', 'status'], name='security_se_organiz_c2e7d9_idx'), models.Index(fields=['organization', 'category'], name='security_se_organiz_170169_idx')],
            },
        ),
    ]
