# Generated by Django 5.2.14 on 2026-07-11 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_compliance_agents_traces"),
        ("security", "0002_securityfinding_fingerprint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitrace",
            name="trace_type",
            field=models.CharField(
                choices=[
                    ("llm_call", "Prompt"),
                    ("tool_call", "Tool Call"),
                    ("agent_action", "Agent Action"),
                    ("retrieval", "RAG"),
                    ("embedding", "Embedding"),
                    ("mcp_tool", "MCP"),
                    ("agent_control", "Agent Control"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ManagedAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_key", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "control_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("quarantined", "Quarantined"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
                ("framework", models.CharField(blank=True, max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_control_action", models.CharField(blank=True, max_length=32)),
                ("last_control_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_agents",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "control_status"],
                        name="security_ma_organiz_10fbb7_idx",
                    )
                ],
                "unique_together": {("organization", "agent_key")},
            },
        ),
    ]
