"""
EEG - HTML Report Generator
Produces a self-contained HTML security report.
"""

import html
import datetime
from eeg.collector import Collector, Finding


SEVERITY_COLORS = {
    "CRITICAL": "#dc2626",
    "HIGH": "#ea580c",
    "MEDIUM": "#ca8a04",
    "LOW": "#2563eb",
    "INFO": "#6b7280",
}


class HTMLReportGenerator:
    """Generate a standalone HTML report from collected findings."""

    def __init__(self, collector: Collector):
        self.collector = collector

    def generate(self) -> str:
        summary = self.collector.get_summary()
        findings = self.collector.get_findings_sorted()
        meta = self.collector.scan_metadata

        findings_html = self._render_findings(findings)
        summary_html = self._render_summary(summary, meta)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>EEG Security Report — {meta.get('cloud_env','').upper()}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }}
  .container {{ max-width: 1100px; margin: 0 auto; }}
  h1 {{ font-size: 2rem; margin-bottom: 0.5rem; color: #38bdf8; }}
  .subtitle {{ color: #94a3b8; margin-bottom: 2rem; }}
  .summary-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 1rem; margin-bottom: 2rem; }}
  .card {{ background: #1e293b; border-radius: 10px; padding: 1.2rem; text-align: center; }}
  .card .num {{ font-size: 2rem; font-weight: 700; }}
  .card .label {{ font-size: 0.85rem; color: #94a3b8; margin-top: 0.3rem; }}
  .finding {{ background: #1e293b; border-left: 4px solid; border-radius: 8px; padding: 1.2rem; margin-bottom: 1rem; }}
  .finding h3 {{ margin-bottom: 0.5rem; font-size: 1rem; }}
  .badge {{ display: inline-block; padding: 2px 10px; border-radius: 4px; font-size: 0.75rem; font-weight: 700; color: #fff; margin-right: 0.5rem; }}
  .meta {{ font-size: 0.82rem; color: #94a3b8; margin-bottom: 0.5rem; }}
  .snippet {{ background: #0f172a; border-radius: 6px; padding: 0.8rem; font-family: monospace; font-size: 0.82rem; overflow-x: auto; margin: 0.5rem 0; white-space: pre-wrap; }}
  .rec {{ background: #1a2332; border-radius: 6px; padding: 0.7rem; margin-top: 0.5rem; font-size: 0.85rem; }}
  .rec strong {{ color: #38bdf8; }}
  footer {{ text-align: center; color: #475569; margin-top: 3rem; font-size: 0.8rem; }}
</style>
</head>
<body>
<div class="container">
  <h1>🛡️ EEG — Extensive Exposure Guard</h1>
  <p class="subtitle">Multi-Cloud AI Security Report &middot; {meta.get('cloud_env','').upper()} &middot; {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</p>
  {summary_html}
  <h2 style="margin:1.5rem 0 1rem;">Findings ({summary['total_findings']})</h2>
  {findings_html if findings_html else '<p style="color:#94a3b8;">No findings — your repository looks clean! ✅</p>'}
  <footer>Generated by EEG (Extensive Exposure Guard) &middot; AI-First Cloud Security</footer>
</div>
</body>
</html>"""

    def _render_summary(self, summary: dict, meta: dict) -> str:
        cards = ""
        for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
            color = SEVERITY_COLORS[sev]
            count = summary["by_severity"][sev]
            cards += f'<div class="card"><div class="num" style="color:{color}">{count}</div><div class="label">{sev}</div></div>'
        cards += f'<div class="card"><div class="num" style="color:#38bdf8">{summary["files_scanned"]}</div><div class="label">Files Scanned</div></div>'
        cards += f'<div class="card"><div class="num" style="color:#38bdf8">{summary["scan_duration_seconds"]}s</div><div class="label">Duration</div></div>'
        
        # Add permission tracking info if there were issues
        completed = summary.get("completed_checks", 0)
        skipped = summary.get("skipped_checks", 0)
        perm_issues = summary.get("permission_issues", 0)
        
        if skipped > 0 or perm_issues > 0:
            cards += f'<div class="card"><div class="num" style="color:#22c55e">{completed}</div><div class="label">Checks Completed</div></div>'
            cards += f'<div class="card"><div class="num" style="color:#f59e0b">{skipped}</div><div class="label">Checks Skipped</div></div>'
        
        return f'<div class="summary-grid">{cards}</div>'

    def _render_findings(self, findings: list) -> str:
        out = ""
        for f in findings:
            color = SEVERITY_COLORS.get(f.severity.value, "#6b7280")
            snippet = html.escape(f.code_snippet[:300]) if f.code_snippet else ""
            owasp = f' &middot; {html.escape(f.owasp_llm)}' if f.owasp_llm else ""
            cwe = f' &middot; {html.escape(f.cwe)}' if f.cwe else ""
            out += f"""
<div class="finding" style="border-color:{color}">
  <h3><span class="badge" style="background:{color}">{f.severity.value}</span> {html.escape(f.message)}</h3>
  <div class="meta">{html.escape(f.rule_id)} &middot; {html.escape(f.category)}{owasp}{cwe}</div>
  <div class="meta">📄 {html.escape(f.file_path)} : line {f.line_number}</div>
  {f'<div class="snippet">{snippet}</div>' if snippet else ''}
  <div class="rec"><strong>Recommendation:</strong> {html.escape(f.recommendation)}</div>
</div>"""
        return out
